### ISSUE TITLE
Support subdocuments

### ISSUE THREAD

**Issue by dotlouis** [yamadapc/mongoose-private-paths#21]
Hi, first of all thanks for this module. It helps me a lot.

I just wanted to report that when nesting subdocument as specified in [Mongoose Doc](http://mongoosejs.com/docs/subdocs.html), the private properties of the subdocument are not removed as they should.

(pseudo code non tested)
```JS

var ChildSchema = mongoose.Schema({
  privateProp: {type: String, private: true},
  publicProp: String
});

var ParentSchema = mongoose.Schema({
  parentPrivateProp: {type: String, private: true},
  parentPublicProp: String,
  embedChild: ChildSchema
});

var Parent = mongoose.model('Parent', ParentSchema);

var p = new Model({
  parentPrivateProp: "hello",
  parentPublicProp: "my name is",
  embedChild: {
    privateProp: "Slim",
    publicProp: "Shady"
  }
});

p.toJSON();
// returns
/*
{
  parentPublicProp: "my name is",
  embedChild: {
    privateProp: "Slim",
    publicProp: "Shady"
  }
}
*/

// while it should return
/*
{
  parentPublicProp: "my name is",
  embedChild: {
    publicProp: "Shady"
  }
}
*/
```

I monkey patched the behavior in the [nestedOmit()](https://github.com/yamadapc/mongoose-private-paths/blob/master/lib/index.js#L114) function by replacing

```JS
    var p = paths[key],
        t;
```

by:
```JS
    var p, t;

	if(_.isObject(paths.tree)){
		p = paths.tree[key];
	}
	else{
		p = paths[key];
	}
```

I don't know if it's the proper way to do it and if it passes tests. I just came with this patch.
I may submit a PR later. For now I just wanted to let you know :)

**Comment by yamadapc** [comment]
That sounds like the proper way to do it, would you kind putting it in a PR and adding a test? Mostrar probably the tests do pass.

I've the impression this will still fail for nested schema arrays.

I'm not really using this in prod. nowadays. The patch you made is in a vendored repostiroy or...?

**Comment by yamadapc** [comment]
Thanks a lot for reporting the issue and submitting a patch!

**Comment by dotlouis** [comment]
You're welcome, thanks for replying :)
I just finished the PR. But github says I don't have the authorization to publish to this repo. (I made a new branch). How should I proceed ?

**Comment by yamadapc** [comment]
Yeah; the usual way with GitHub is you either:
- Click "fork" to create your version of the repo
- `git remote add dotlouis git@github.com:dotlouis/mongoose-private-paths && git push dotlouis <branch>`
- Then open a pull-request

Or if you have [`hub`](https://github.com/github/hub) installed:
```
$ hub fork
$ git push dotlouis <branch>
$ hub pull-request
```

**Comment by dotlouis** [comment]
Thanks a lot for your help ! I've submitted the PR

**Comment by yamadapc** [comment]
Awesomeness! In `0.7.0`
