### ISSUE TITLE
Direct type declaration fails isPrivate

### ISSUE THREAD

**Issue by voliva** [yamadapc/mongoose-private-paths#8]
If you declare an schema such as:

    var userSchema = new Schema({
        username: String,
	_password: String
    })
That's perfectly valid for mongoose, `toJSON` will show the field `_password` because it's not detected properly in `isPrivate` method.

Atm, this is the `if`that fails:

    else if(_.isObject(node) && !node.type && !node.getters) {
since node is the type String (internally that's a function) and underscore returns isObject as true.

Maybe the solution is like

    else if(_.isObject(node) && !_.isFunction(node) && !node.type && !node.getters) {

**Comment by yamadapc** [comment]
Yeah... I'll think of something, thanks for the report! A PR would be greatly appreciated, since I'm not that free on time at the moment.
